INSERT INTO matrizescalas (categoria, nombrematriz, valor) VALUES
('CLASIFICACIÓN EN INTERACCIÓN MUSICAL (CIM)', 'SIN COMUNICACIÓN', '1'),
('CLASIFICACIÓN EN INTERACCIÓN MUSICAL (CIM)', 'CONTACTO DE UN SOLO LADO: NO HAY RESPUESTA DEL PARTICIPANTE', '2'),
('CLASIFICACIÓN EN INTERACCIÓN MUSICAL (CIM)', 'CONTACTO DE UN SOLO LADO: NO HAY RESPUESTA MUSICAL DEL PARTICIPANTE', '3'),
('CLASIFICACIÓN EN INTERACCIÓN MUSICAL (CIM)', 'RESPUESTA MUSICAL AUTODIRIGIDA DEL PARTICIPANTE', '4'),
('CLASIFICACIÓN EN INTERACCIÓN MUSICAL (CIM)', 'RESPUESTA TENUE DEL PARTICIPANTE', '5'),
('CLASIFICACIÓN EN INTERACCIÓN MUSICAL (CIM)', 'RESPUESTA MUSICALMENTE DIRIGIDA Y SOSTENIDA', '6'),
('CLASIFICACIÓN EN INTERACCIÓN MUSICAL (CIM)', 'ESTABLECIENDO CONTACTO MUTUO', '7'),
('CLASIFICACIÓN EN INTERACCIÓN MUSICAL (CIM)', 'EXTENDIENDO EL CONTACTO MUTUO', '8'),
('CLASIFICACIÓN EN INTERACCIÓN MUSICAL (CIM)', 'ASOCIACIÓN MUSICAL', '9');

INSERT INTO matrizescalas (categoria, nombrematriz, valor) VALUES
('ESCALA DE RELACIONES INTERMUSICALES (ERI)', 'NO LOS REGISTRA', '1'),
('ESCALA DE RELACIONES INTERMUSICALES (ERI)', 'LOS REGISTRA', '2'),
('ESCALA DE RELACIONES INTERMUSICALES (ERI)', 'LOS MANIPULA', '3'),
('ESCALA DE RELACIONES INTERMUSICALES (ERI)', 'LOS EXPLORA', '4'),
('ESCALA DE RELACIONES INTERMUSICALES (ERI)', 'PERSISTE EN LA UTILIZACIÓN', '5'),
('ESCALA DE RELACIONES INTERMUSICALES (ERI)', 'REALIZA ALGUNA ACTIVIDAD A PARTIR DE ELLOS', '6'),
('ESCALA DE RELACIONES INTERMUSICALES (ERI)', 'LES DA UN USO MUSICAL BREVE', '7'),
('ESCALA DE RELACIONES INTERMUSICALES (ERI)', 'LES DA UN USO MUSICAL INTENCIONAL PROLONGADO', '8'),
('ESCALA DE RELACIONES INTERMUSICALES (ERI)', 'LES DA UN USO MUSICAL CON UNA INTENCIÓN INTERMUSICAL', '9');

INSERT INTO matrizescalas (categoria, nombrematriz, valor) VALUES
('MOMENTO', 'BIENVENIDA', ''),
('MOMENTO', 'EXPRESIÓN CORPORAL', ''),
('MOMENTO', 'RITMO Y ESPACIO', ''),
('MOMENTO', 'DANZA LIBRE', ''),
('MOMENTO', 'RELAJACIÓN', ''),
('MOMENTO', 'DESPEDIDA', ''),
('MOMENTO', 'RITMICO', ''),
('MOMENTO', 'MELÓDICO', ''),
('MOMENTO', 'ISO', ''),
('MOMENTO', 'ARMÓNICO', ''),
('MOMENTO', 'ABSTRACCIÓN', '');

INSERT INTO matrizescalas (categoria, nombrematriz, valor) VALUES
('OBJETIVOS', 'COMPORTAMIENTOS RESTRICTIVOS', ''),
('OBJETIVOS', 'INTERACCIÓN SOCIAL COGNITIVA', ''),
('OBJETIVOS', 'PERCEPCIÓN EXPLORACIÓN RITMICA', ''),
('OBJETIVOS', 'PERCEPCIÓN EXPLORACIÓN SONORA', ''),
('OBJETIVOS', 'EXPLORACIÓN VOCAL', ''),
('OBJETIVOS', 'MOVIMIENTO CORPORAL CON MÚSICA', '');


INSERT INTO matrizescalas (categoria, nombrematriz, valor) VALUES
('RECURSOS MUSICALES', 'HOLA MUSICOS MY', ''),
('RECURSOS MUSICALES', 'ADIOS DO', ''),
('RECURSOS MUSICALES', 'LA BAMBA', ''),
('RECURSOS MUSICALES', 'JAZZ EN G', ''),
('RECURSOS MUSICALES', 'EN LA GRANJA LI', ''),
('RECURSOS MUSICALES', 'BARCO DE PAPEL', ''),
('RECURSOS MUSICALES', 'PINGUINOS MY', ''),
('RECURSOS MUSICALES', 'CARAMELOS DE FRESA MY', ''),
('RECURSOS MUSICALES', 'HOLA CUERPO', ''),
('RECURSOS MUSICALES', 'ZAPATITOS', ''),
('RECURSOS MUSICALES', 'ZAPATOS GIGANTES', ''),
('RECURSOS MUSICALES', 'UNA GRAN SOPA', ''),
('RECURSOS MUSICALES', 'BARQUITO PEQUEÑITO AM', ''),
('RECURSOS MUSICALES', 'BARCO DE PAPEL', ''),
('RECURSOS MUSICALES', 'MI BICI ROJA', ''),
('RECURSOS MUSICALES', 'REMANDO EL RIO LO', ''),
('RECURSOS MUSICALES', 'AGUILA ROJA MT', ''),
('RECURSOS MUSICALES', 'DUENDECILLO SOÑADOR FR', ''),
('RECURSOS MUSICALES', 'VOY EN MOVIMIENTO', ''),
('RECURSOS MUSICALES', 'LA SOPA DO', ''),
('RECURSOS MUSICALES', 'GUACAMOLE II', ''),
('RECURSOS MUSICALES', 'MIRA MIRA', ''),
('RECURSOS MUSICALES', 'PIÑA Y COCO II', ''),
('RECURSOS MUSICALES', 'LISTOS YA', ''),
('RECURSOS MUSICALES', 'ME ESCONDI AM', ''),
('RECURSOS MUSICALES', 'GATITO', '');

INSERT INTO matrizescalas (categoria, nombrematriz, valor) VALUES
('ENFASIS MUSICAL', 'PATRONES TONALES', ''),
('ENFASIS MUSICAL', 'PATRONES RÍTMICOS', ''),
('ENFASIS MUSICAL', 'ENCUADRE JAZZ', ''),
('ENFASIS MUSICAL', 'ENCUADRE LATINO', ''),
('ENFASIS MUSICAL', 'ENCUADRE MODAL', ''),
('ENFASIS MUSICAL', 'LIVE MOTIVE', ''),
('ENFASIS MUSICAL', 'IMPR. TEMÁTICA RITMICA', ''),
('ENFASIS MUSICAL', 'IMPR. TEMÁTICA MELÓDICA', '');

INSERT INTO matrizescalas (categoria, nombrematriz, valor) VALUES
('ENFOQUE', 'MLT GORDON', ''),
('ENFOQUE', 'DALCROZE', ''),
('ENFOQUE', 'WILLIEMS', ''),
('ENFOQUE', 'GIM', ''),
('ENFOQUE', 'MT CREATIVA', ''),
('ENFOQUE', 'MT CONDUCTUAL', '');

INSERT INTO matrizescalas (categoria, nombrematriz, valor) VALUES
('ETAPA MLT', 'ACUL-E1: ABSORCIÓN', ''),
('ETAPA MLT', 'ACUL-E2: RESPUESTA SIN INTENCIÓN', ''),
('ETAPA MLT', 'ACUL-E3: RESPUESTA INTENCIONADA', ''),
('ETAPA MLT', 'IMI-E4: SALIENDO DEL EGOCENTRISMO', ''),
('ETAPA MLT', 'IMI-E5: CAPTANDO EL SENTIDO', ''),
('ETAPA MLT', 'ASI-E6: INTROSPECCIÓN', ''),
('ETAPA MLT', 'ASI-E7: COORDINACIÓN', '');



